name: route_dev
channels:
  - conda-forge
  - anaconda
dependencies:
  - conda-forge::python=3.7.8
  - conda-forge::numpy=1.19.1
  - conda-forge::matplotlib=3.3.0
  - conda-forge::pip=20.2.1
  - conda-forge::geopy=2.0.0
  - conda-forge::geopandas=0.8.1
  - conda-forge::xlrd=1.2.0
  - conda-forge::openpyxl=3.0.4
  - conda-forge::XlsxWriter=1.3.2
  - conda-forge::pyproj=2.6.1
  - conda-forge::jupyterlab=2.2.4
  - conda-forge::hdbscan=0.8.26
  - conda-forge::psycopg2=2.8.5
  - conda-forge::sqlalchemy=1.3.19
  - conda-forge::psutil=5.7.2
  - conda-forge::django=3.0.6
  - conda-forge::django-cors-headers=3.4.0
  - conda-forge::djangorestframework=3.12.0
  - conda-forge::pre-commit=2.9.2
  - conda-forge::polyline=1.4.0
  - conda-forge::folium=0.11.0
    # Linters y herramientas
  - conda-forge::pylint=2.5.2
  - conda-forge::flake8=3.8.3
  - conda-forge::autopep8=1.5.3
  - conda-forge::rope=0.17.0
  - conda-forge::black=19.10b0
  - conda-forge::pep257=0.7.0
  - conda-forge::pylama=7.7.1
  - conda-forge::mypy=0.782
  # Documentación
  - conda-forge::sphinx=3.2.1
  - conda-forge::perl=5.26.2
  - pip:
      - ortools==7.5.7466
